import { useState } from "react";
import { useShop } from "../store/ShopStore";
import { Icon } from "../components/Icon";
import { currency, dateTime, whatsappUrl } from "../lib/utils";
import { navigate } from "../lib/router";

export function Account() {
  const { currentUser, data, logout } = useShop();
  const [tab, setTab] = useState<"orders" | "evaluations" | "messages" | "profile">("orders");
  if (!currentUser) { window.setTimeout(() => navigate("/entrar"), 0); return null; }
  const orders = data.orders.filter((order) => order.userId === currentUser.id);
  const evaluations = data.evaluations.filter((item) => item.userId === currentUser.id);
  const messages = data.messages.filter((item) => item.userId === currentUser.id);

  return <section className="page-section account-page"><div className="container"><div className="account-header"><div><span>MINHA CONTA</span><h1>Olá, {currentUser.name.split(" ")[0]}.</h1><p>Acompanhe seus pedidos, avaliações e conversas.</p></div><button className="btn secondary" onClick={() => { logout(); navigate("/"); }}><Icon name="logout"/> Sair</button></div><div className="account-layout"><aside className="account-nav"><button className={tab === "orders" ? "active" : ""} onClick={() => setTab("orders")}><Icon name="bag"/> Pedidos <b>{orders.length}</b></button><button className={tab === "evaluations" ? "active" : ""} onClick={() => setTab("evaluations")}><Icon name="camera"/> Avaliações <b>{evaluations.length}</b></button><button className={tab === "messages" ? "active" : ""} onClick={() => setTab("messages")}><Icon name="message"/> Mensagens <b>{messages.length}</b></button><button className={tab === "profile" ? "active" : ""} onClick={() => setTab("profile")}><Icon name="user"/> Perfil</button></aside><div className="account-content">
    {tab === "orders" && <section><div className="content-title"><div><h2>Meus pedidos</h2><p>Pedidos enviados para confirmação do vendedor.</p></div><button className="btn primary" onClick={() => navigate("/produtos")}>Comprar produtos</button></div>{orders.length ? <div className="order-cards">{orders.map((order) => <article key={order.id}><div className="order-card-top"><div><small>{dateTime(order.createdAt)}</small><strong>#{order.code}</strong></div><span data-status={order.status}>{order.status}</span></div><div className="order-items-mini">{order.items.map((item) => <div key={item.productId}><span>{item.quantity}x</span><strong>{item.name}</strong><b>{currency(item.unitPrice * item.quantity)}</b></div>)}</div><div className="order-card-bottom"><span>{order.shipping.label}</span><strong>Total estimado: {currency(order.total)}</strong></div>{order.trackingCode && <div className="tracking">Rastreamento: <strong>{order.trackingCode}</strong></div>}<a href={whatsappUrl(data.settings.whatsapp, `Olá! Gostaria de falar sobre o pedido #${order.code}.`)} target="_blank" rel="noreferrer">Falar com o vendedor <Icon name="arrow" size={16}/></a></article>)}</div> : <Empty title="Nenhum pedido enviado" text="Monte seu carrinho e envie uma solicitação ao vendedor." action="Ver produtos" path="/produtos"/>}</section>}
    {tab === "evaluations" && <section><div className="content-title"><div><h2>Avaliações de iPhone</h2><p>Acompanhe as respostas do vendedor.</p></div><button className="btn primary" onClick={() => navigate("/avaliar-iphone")}>Nova avaliação</button></div>{evaluations.length ? <div className="evaluation-cards">{evaluations.map((item) => <article key={item.id}><div><small>{dateTime(item.createdAt)}</small><h3>{item.model} • {item.storage}</h3><p>Bateria: {item.batteryHealth}% • Tela: {item.screenState}</p></div><span>{item.status}</span>{item.estimatedValue && <strong>Estimativa: {currency(item.estimatedValue)}</strong>}{item.adminMessage && <blockquote>{item.adminMessage}</blockquote>}</article>)}</div> : <Empty title="Nenhuma avaliação" text="Envie os dados e fotos do seu aparelho." action="Avaliar iPhone" path="/avaliar-iphone"/>}</section>}
    {tab === "messages" && <section><div className="content-title"><div><h2>Mensagens</h2><p>Conversas abertas pelo site.</p></div><button className="btn primary" onClick={() => navigate("/contato")}>Nova mensagem</button></div>{messages.length ? <div className="message-cards">{messages.map((item) => <article key={item.id}><div><small>{dateTime(item.createdAt)} • {item.status}</small><h3>{item.subject}</h3><p>{item.message}</p></div>{item.reply && <blockquote><strong>Resposta do vendedor</strong>{item.reply}</blockquote>}</article>)}</div> : <Empty title="Nenhuma mensagem" text="Fale com o vendedor sobre um produto ou pedido." action="Enviar mensagem" path="/contato"/>}</section>}
    {tab === "profile" && <section><div className="content-title"><div><h2>Dados da conta</h2><p>Informações usadas no atendimento.</p></div></div><div className="profile-card"><div><small>Nome</small><strong>{currentUser.name}</strong></div><div><small>E-mail</small><strong>{currentUser.email}</strong></div><div><small>WhatsApp</small><strong>{currentUser.phone}</strong></div><div><small>Endereços salvos</small><strong>{currentUser.addresses.length}</strong></div></div></section>}
  </div></div></div></section>;
}

function Empty({ title, text, action, path }: { title: string; text: string; action: string; path: string }) {
  return <div className="empty-panel small"><Icon name="box" size={31}/><h3>{title}</h3><p>{text}</p><button className="btn secondary" onClick={() => navigate(path)}>{action}</button></div>;
}
